services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d/scripts
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  backend:
    build:
      context: ./backend
      target: prod
    depends_on:
      - db
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:5005:5005
      - 127.0.0.1:35729:35729
    environment:
      - PUBLIC_KEY_PATH=${PUBLIC_KEY_PATH}
      - PRIVATE_KEY_PATH=${PRIVATE_KEY_PATH}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - BASE_URL=${BASE_URL}
    volumes:
      - ./config:/app/config:ro
  gateway:
    image: nginx:1.25.3-alpine
    depends_on:
      - db
    volumes:
      - ./gateway/nginx:/etc/nginx:ro
      - ./gateway/static:/static:ro
      - ./gateway/logs:/logs
    ports:
      - "127.0.0.1:8000:80"
