/** @type {import('tailwindcss').Config} */
module.exports = {
  content: {
    relative: true,
    files: ["./src/main/resources/templates/**/*.html"],
  },
  theme: {
    fontFamily: {
      sans: ["Roboto", "sans-serif"],
    },
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "hsl(var(--color-primary-50))",
          100: "hsl(var(--color-primary-100))",
          200: "hsl(var(--color-primary-200))",
          300: "hsl(var(--color-primary-300))",
          400: "hsl(var(--color-primary-400))",
          500: "hsl(var(--color-primary-500))",
          600: "hsl(var(--color-primary-600))",
          700: "hsl(var(--color-primary-700))",
          800: "hsl(var(--color-primary-100))",
          900: "hsl(var(--color-primary-900))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          50: "hsl(var(--color-secondary-50))",
          100: "hsl(var(--color-secondary-100))",
          200: "hsl(var(--color-secondary-200))",
          300: "hsl(var(--color-secondary-300))",
          400: "hsl(var(--color-secondary-400))",
          500: "hsl(var(--color-secondary-500))",
          600: "hsl(var(--color-secondary-600))",
          700: "hsl(var(--color-secondary-700))",
          800: "hsl(var(--color-secondary-100))",
          900: "hsl(var(--color-secondary-900))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
          50: "hsl(var(--color-destructive-50))",
          100: "hsl(var(--color-destructive-100))",
          200: "hsl(var(--color-destructive-200))",
          300: "hsl(var(--color-destructive-300))",
          400: "hsl(var(--color-destructive-400))",
          500: "hsl(var(--color-destructive-500))",
          600: "hsl(var(--color-destructive-600))",
          700: "hsl(var(--color-destructive-700))",
          800: "hsl(var(--color-destructive-800))",
          900: "hsl(var(--color-destructive-900))",
          950: "hsl(var(--color-destructive-950))",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
      },
    },
  },
  plugins: [],
};
