server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: debug
        security: debug
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
    net:
      ttddyy:
        dsproxy:
          listener: debug

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate

issuetracker:
  insert-fake-data: false