server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: debug
        security: debug

spring:
  datasource:
    url: "jdbc:sqlite:file:/home/oscar/projects/issue-tracker/issuetracker/db/dev.db"
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: password

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
      globally-quoted-identifiers: true
