server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: debug
        security: debug
        data: debug

spring:
  datasource:
    url: 'jdbc:sqlite:file:${SQLITE_FILE_PATH}'
    driver-class-name: org.sqlite.JDBC
    username: ''
    password: ''

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
      globally-quoted-identifiers: true
